"""Scientific name -> Japanese common name (和名) lookup table.

Perch 2.0's species head is keyed by binomial scientific names (eBird/Clements
style, e.g. ``Zosterops japonicus``). This maps the ones common in Japan to their
和名 (katakana) so the UI can show a familiar name in the "種" column. Species not
listed here fall back to the scientific name — this is intentionally a curated
subset of a few hundred common taxa, not the full ~14.8k class list.

Keys must match :func:`backend.labels.scientific_name` output ("Genus species").
Where a species' taxonomy is unstable, common synonyms are included as extra keys
pointing to the same 和名, to maximise hits against whatever name Perch emits.
"""

from __future__ import annotations

# fmt: off
WAMEI: dict[str, str] = {
    # --- ガンカモ類 Anatidae ---------------------------------------------
    "Cygnus cygnus": "オオハクチョウ",
    "Cygnus columbianus": "コハクチョウ",
    "Anser albifrons": "マガン",
    "Anser fabalis": "ヒシクイ",
    "Branta bernicla": "コクガン",
    "Aix galericulata": "オシドリ",
    "Tadorna tadorna": "ツクシガモ",
    "Spatula clypeata": "ハシビロガモ",
    "Anas clypeata": "ハシビロガモ",
    "Spatula querquedula": "シマアジ",
    "Mareca strepera": "オカヨシガモ",
    "Anas strepera": "オカヨシガモ",
    "Mareca penelope": "ヒドリガモ",
    "Anas penelope": "ヒドリガモ",
    "Anas platyrhynchos": "マガモ",
    "Anas zonorhyncha": "カルガモ",
    "Anas poecilorhyncha": "カルガモ",
    "Anas acuta": "オナガガモ",
    "Anas crecca": "コガモ",
    "Aythya ferina": "ホシハジロ",
    "Aythya fuligula": "キンクロハジロ",
    "Aythya marila": "スズガモ",
    "Bucephala clangula": "ホオジロガモ",
    "Mergellus albellus": "ミコアイサ",
    "Mergus merganser": "カワアイサ",
    "Mergus serrator": "ウミアイサ",
    # --- キジ類 Phasianidae ----------------------------------------------
    "Phasianus versicolor": "キジ",
    "Phasianus colchicus": "キジ",
    "Bambusicola thoracicus": "コジュケイ",
    "Coturnix japonica": "ウズラ",
    # --- カイツブリ類 Podicipedidae --------------------------------------
    "Tachybaptus ruficollis": "カイツブリ",
    "Podiceps cristatus": "カンムリカイツブリ",
    "Podiceps grisegena": "アカエリカイツブリ",
    # --- ハト類 Columbidae -----------------------------------------------
    "Streptopelia orientalis": "キジバト",
    "Columba janthina": "カラスバト",
    "Columba livia": "カワラバト",
    "Treron sieboldii": "アオバト",
    "Spilopelia chinensis": "カノコバト",
    # --- カッコウ類 Cuculidae --------------------------------------------
    "Cuculus canorus": "カッコウ",
    "Cuculus optatus": "ツツドリ",
    "Cuculus saturatus": "ツツドリ",
    "Cuculus poliocephalus": "ホトトギス",
    "Hierococcyx hyperythrus": "ジュウイチ",
    # --- アマツバメ類 Apodidae -------------------------------------------
    "Apus pacificus": "アマツバメ",
    "Hirundapus caudacutus": "ハリオアマツバメ",
    # --- クイナ類 Rallidae -----------------------------------------------
    "Gallinula chloropus": "バン",
    "Fulica atra": "オオバン",
    "Rallus aquaticus": "クイナ",
    "Rallus indicus": "クイナ",
    "Porzana fusca": "ヒクイナ",
    "Zapornia fusca": "ヒクイナ",
    # --- ツル類 Gruidae --------------------------------------------------
    "Grus japonensis": "タンチョウ",
    "Grus grus": "クロヅル",
    "Grus vipio": "マナヅル",
    "Grus monacha": "ナベヅル",
    # --- チドリ・シギ類 Charadriiformes ----------------------------------
    "Vanellus vanellus": "タゲリ",
    "Charadrius dubius": "コチドリ",
    "Charadrius alexandrinus": "シロチドリ",
    "Charadrius placidus": "イカルチドリ",
    "Scolopax rusticola": "ヤマシギ",
    "Gallinago gallinago": "タシギ",
    "Actitis hypoleucos": "イソシギ",
    "Tringa ochropus": "クサシギ",
    "Tringa glareola": "タカブシギ",
    "Numenius arquata": "ダイシャクシギ",
    "Larus crassirostris": "ウミネコ",
    "Larus canus": "カモメ",
    "Larus vegae": "セグロカモメ",
    "Chroicocephalus ridibundus": "ユリカモメ",
    "Sterna hirundo": "アジサシ",
    # --- アビ・ミズナギドリ類 --------------------------------------------
    "Calonectris leucomelas": "オオミズナギドリ",
    # --- ウ類・サギ類 ----------------------------------------------------
    "Phalacrocorax carbo": "カワウ",
    "Phalacrocorax capillatus": "ウミウ",
    "Ardea cinerea": "アオサギ",
    "Ardea alba": "ダイサギ",
    "Egretta alba": "ダイサギ",
    "Ardea intermedia": "チュウサギ",
    "Egretta intermedia": "チュウサギ",
    "Egretta garzetta": "コサギ",
    "Bubulcus ibis": "アマサギ",
    "Nycticorax nycticorax": "ゴイサギ",
    "Butorides striata": "ササゴイ",
    "Ixobrychus sinensis": "ヨシゴイ",
    "Botaurus stellaris": "サンカノゴイ",
    "Gorsachius goisagi": "ミゾゴイ",
    # --- トキ・コウノトリ類 ----------------------------------------------
    "Nipponia nippon": "トキ",
    "Platalea minor": "クロツラヘラサギ",
    "Ciconia boyciana": "コウノトリ",
    # --- タカ類 Accipitriformes ------------------------------------------
    "Pandion haliaetus": "ミサゴ",
    "Pernis ptilorhynchus": "ハチクマ",
    "Milvus migrans": "トビ",
    "Haliaeetus albicilla": "オジロワシ",
    "Haliaeetus pelagicus": "オオワシ",
    "Spilornis cheela": "カンムリワシ",
    "Circus spilonotus": "チュウヒ",
    "Circus cyaneus": "ハイイロチュウヒ",
    "Accipiter gentilis": "オオタカ",
    "Accipiter nisus": "ハイタカ",
    "Accipiter gularis": "ツミ",
    "Accipiter soloensis": "アカハラダカ",
    "Butastur indicus": "サシバ",
    "Buteo japonicus": "ノスリ",
    "Buteo buteo": "ノスリ",
    "Buteo hemilasius": "オオノスリ",
    "Buteo lagopus": "ケアシノスリ",
    "Nisaetus nipalensis": "クマタカ",
    "Aquila chrysaetos": "イヌワシ",
    "Clanga clanga": "カラフトワシ",
    # --- フクロウ類 Strigiformes -----------------------------------------
    "Otus sunia": "コノハズク",
    "Otus semitorques": "オオコノハズク",
    "Bubo blakistoni": "シマフクロウ",
    "Strix uralensis": "フクロウ",
    "Ninox japonica": "アオバズク",
    "Ninox scutulata": "アオバズク",
    "Asio otus": "トラフズク",
    "Asio flammeus": "コミミズク",
    "Glaucidium passerinum": "スズメフクロウ",
    # --- ブッポウソウ・カワセミ類 ----------------------------------------
    "Alcedo atthis": "カワセミ",
    "Halcyon coromanda": "アカショウビン",
    "Halcyon pileata": "ヤマショウビン",
    "Megaceryle lugubris": "ヤマセミ",
    "Eurystomus orientalis": "ブッポウソウ",
    "Upupa epops": "ヤツガシラ",
    # --- キツツキ類 Picidae ----------------------------------------------
    "Jynx torquilla": "アリスイ",
    "Yungipicus kizuki": "コゲラ",
    "Dendrocopos kizuki": "コゲラ",
    "Picoides kizuki": "コゲラ",
    "Dendrocopos major": "アカゲラ",
    "Dendrocopos leucotos": "オオアカゲラ",
    "Picus awokera": "アオゲラ",
    "Picus canus": "ヤマゲラ",
    "Dryocopus martius": "クマゲラ",
    # --- ハヤブサ類 Falconidae -------------------------------------------
    "Falco tinnunculus": "チョウゲンボウ",
    "Falco amurensis": "アカアシチョウゲンボウ",
    "Falco columbarius": "コチョウゲンボウ",
    "Falco subbuteo": "チゴハヤブサ",
    "Falco peregrinus": "ハヤブサ",
    # --- モズ類 Laniidae -------------------------------------------------
    "Lanius bucephalus": "モズ",
    "Lanius cristatus": "アカモズ",
    "Lanius tigrinus": "チゴモズ",
    "Lanius sphenocercus": "オオモズ",
    # --- カラス類 Corvidae -----------------------------------------------
    "Garrulus glandarius": "カケス",
    "Perisoreus infaustus": "シベリアカケス",
    "Cyanopica cyanus": "オナガ",
    "Pica pica": "カササギ",
    "Nucifraga caryocatactes": "ホシガラス",
    "Corvus dauuricus": "コクマルガラス",
    "Corvus frugilegus": "ミヤマガラス",
    "Corvus corone": "ハシボソガラス",
    "Corvus macrorhynchos": "ハシブトガラス",
    # --- カラ・ツバメ・ヒバリ類 ------------------------------------------
    "Remiz consobrinus": "ツリスガラ",
    "Sittiparus varius": "ヤマガラ",
    "Parus varius": "ヤマガラ",
    "Poecile montanus": "コガラ",
    "Parus montanus": "コガラ",
    "Poecile palustris": "ハシブトガラ",
    "Periparus ater": "ヒガラ",
    "Parus ater": "ヒガラ",
    "Parus minor": "シジュウカラ",
    "Parus major": "シジュウカラ",
    "Alauda arvensis": "ヒバリ",
    "Riparia riparia": "ショウドウツバメ",
    "Hirundo rustica": "ツバメ",
    "Cecropis daurica": "コシアカツバメ",
    "Delichon dasypus": "イワツバメ",
    # --- ヒヨドリ・ウグイス・エナガ類 ------------------------------------
    "Hypsipetes amaurotis": "ヒヨドリ",
    "Pycnonotus sinensis": "シロガシラ",
    "Cettia diphone": "ウグイス",
    "Horornis diphone": "ウグイス",
    "Urosphena squameiceps": "ヤブサメ",
    "Aegithalos caudatus": "エナガ",
    # --- ムシクイ類 Phylloscopidae ---------------------------------------
    "Phylloscopus borealis": "メボソムシクイ",
    "Phylloscopus xanthodryas": "メボソムシクイ",
    "Phylloscopus coronatus": "センダイムシクイ",
    "Phylloscopus occipitalis": "カンムリムシクイ",
    "Phylloscopus inornatus": "キマユムシクイ",
    "Phylloscopus fuscatus": "ムジセッカ",
    "Phylloscopus proregulus": "キクイタダキムシクイ",
    # --- ヨシキリ・セッカ類 ----------------------------------------------
    "Acrocephalus arundinaceus": "オオヨシキリ",
    "Acrocephalus orientalis": "オオヨシキリ",
    "Acrocephalus bistrigiceps": "コヨシキリ",
    "Locustella lanceolata": "マキノセンニュウ",
    "Locustella ochotensis": "シマセンニュウ",
    "Helopsaltes ochotensis": "シマセンニュウ",
    "Cisticola juncidis": "セッカ",
    # --- メジロ・チメドリ類 ----------------------------------------------
    "Zosterops japonicus": "メジロ",
    "Zosterops erythropleurus": "チョウセンメジロ",
    "Sinosuthora webbiana": "ダルマエナガ",
    # --- キクイタダキ・ゴジュウカラ・キバシリ ----------------------------
    "Regulus regulus": "キクイタダキ",
    "Sitta europaea": "ゴジュウカラ",
    "Certhia familiaris": "キバシリ",
    "Troglodytes troglodytes": "ミソサザイ",
    # --- ムクドリ類 Sturnidae --------------------------------------------
    "Spodiopsar cineraceus": "ムクドリ",
    "Sturnus cineraceus": "ムクドリ",
    "Agropsar philippensis": "コムクドリ",
    "Sturnia philippensis": "コムクドリ",
    "Spodiopsar sericeus": "ギンムクドリ",
    "Sturnus vulgaris": "ホシムクドリ",
    # --- ヒタキ・ツグミ類 Muscicapidae / Turdidae ------------------------
    "Turdus pallidus": "シロハラ",
    "Turdus eunomus": "ツグミ",
    "Turdus naumanni": "ツグミ",
    "Turdus cardis": "クロツグミ",
    "Turdus chrysolaus": "アカハラ",
    "Turdus obscurus": "マミチャジナイ",
    "Geokichla sibirica": "マミジロ",
    "Zoothera aurea": "トラツグミ",
    "Zoothera dauma": "トラツグミ",
    "Monticola solitarius": "イソヒヨドリ",
    "Larvivora akahige": "コマドリ",
    "Luscinia akahige": "コマドリ",
    "Larvivora cyane": "コルリ",
    "Luscinia cyane": "コルリ",
    "Calliope calliope": "ノゴマ",
    "Luscinia calliope": "ノゴマ",
    "Tarsiger cyanurus": "ルリビタキ",
    "Phoenicurus auroreus": "ジョウビタキ",
    "Saxicola stejnegeri": "ノビタキ",
    "Saxicola torquatus": "ノビタキ",
    "Saxicola maurus": "ノビタキ",
    "Muscicapa griseisticta": "エゾビタキ",
    "Muscicapa sibirica": "サメビタキ",
    "Muscicapa dauurica": "コサメビタキ",
    "Ficedula narcissina": "キビタキ",
    "Ficedula mugimaki": "ムギマキ",
    "Ficedula zanthopygia": "マミジロキビタキ",
    "Cyanoptila cyanomelana": "オオルリ",
    "Cyanoptila cumatilis": "オオルリ",
    # --- スズメ・セキレイ・ヒワ・ホオジロ類 ------------------------------
    "Passer montanus": "スズメ",
    "Passer domesticus": "イエスズメ",
    "Passer rutilans": "ニュウナイスズメ",
    "Prunella modularis": "ヨーロッパカヤクグリ",
    "Prunella rubida": "カヤクグリ",
    "Motacilla alba": "ハクセキレイ",
    "Motacilla grandis": "セグロセキレイ",
    "Motacilla cinerea": "キセキレイ",
    "Motacilla flava": "ツメナガセキレイ",
    "Dendronanthus indicus": "イワミセキレイ",
    "Anthus hodgsoni": "ビンズイ",
    "Anthus rubescens": "タヒバリ",
    "Anthus richardi": "マミジロタヒバリ",
    "Fringilla montifringilla": "アトリ",
    "Chloris sinica": "カワラヒワ",
    "Carduelis sinica": "カワラヒワ",
    "Spinus spinus": "マヒワ",
    "Carduelis spinus": "マヒワ",
    "Acanthis flammea": "ベニヒワ",
    "Carpodacus sibiricus": "ベニマシコ",
    "Uragus sibiricus": "ベニマシコ",
    "Carpodacus roseus": "オオマシコ",
    "Pyrrhula pyrrhula": "ウソ",
    "Coccothraustes coccothraustes": "シメ",
    "Eophona personata": "イカル",
    "Eophona migratoria": "コイカル",
    "Emberiza cioides": "ホオジロ",
    "Emberiza spodocephala": "アオジ",
    "Emberiza elegans": "ミヤマホオジロ",
    "Emberiza rustica": "カシラダカ",
    "Emberiza sulphurata": "ノジコ",
    "Emberiza variabilis": "クロジ",
    "Emberiza schoeniclus": "オオジュリン",
    "Emberiza fucata": "ホオアカ",
    "Emberiza yessoensis": "コジュリン",
    "Emberiza pusilla": "コホオアカ",
    "Emberiza chrysophrys": "キマユホオジロ",
    "Emberiza tristrami": "シロハラホオジロ",
    "Plectrophenax nivalis": "ユキホオジロ",
}
# fmt: on
